# fly.toml
app = "tai-ixyqrg"
primary_region = "den"

[build]
  # uses your Dockerfile automatically

[env]
  DATA_ROOT = "/var/appdata"
  PORT = "8080"

[[mounts]]
  source = "data"
  destination = "/var/appdata"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
